### ISSUE TITLE
About results

### ISSUE THREAD

**Issue by jpnyns** [RuiPedroDev/Stalkiana#1]
Thanks for your work,

I noticed that you saved the query of each account on the same txt, I think it would be very good if you could save it in a different folder for each account.

Example:

\Desktop\Stalkiana\user-messi\11.11.23 result.txt
\Desktop\Stalkiana\user-ruipedrodev\10.11.23 result.txt

and I don't know why, but the number of followers and followers is usually a few people less than the normal number, what is the reason for this?

**Comment by RuiBorgesDev** [comment]
Hi, thanks for bringing up the issue. The suggestion to store logs in different folders is a great idea, and I will implement that.

Regarding the number of followers being slightly less than the normal count, that is not expected behavior. Could you provide an example of an account where this issue occurs?

**Comment by jpnyns** [comment]
this is a slightly different example but as you can see below, it's said following count change but in result.txt said no change.
![Capture](https://github.com/RuiPedroDev/Stalkiana/assets/137651666/46a14612-6d5d-4a4a-b241-c7ef492ba2c3)
![Capture2](https://github.com/RuiPedroDev/Stalkiana/assets/137651666/0723957b-8cee-4f49-ae54-b0d2405306d7)

**Comment by RuiBorgesDev** [comment]
Thanks for reporting the bug, I just finished fixing it, it turns out the way I was fetching the users was not consistent and sometimes I fetched the same user twice, now it should be fixed.

**Comment by jpnyns** [comment]
Thank you !!!
